### ISSUE TITLE
Color de fondo en citas en modo oscuro es igual que el de fondo del foro

### ISSUE THREAD

**Issue by Saturos1990** [pdp-devs/fc-material-design#10]
Desde esta mañana cada vez que veo una cita en el modo oscuro, el fondo es del mismo color que el fondo de forocoches, lo cual hace difícil poder identificar una cita.

**Comment by bigsmileling** [comment]
También lo hace con el fondo claro.

**Comment by Saturos1990** [comment]
> También lo hace con el fondo claro.

Creo que lo que se han ido son los bordes de los cuadros de las citas, de ahí que se vea tan extraño. No sé si los desarrolladores aún seguirán en activo con el tema.

**Comment by jbonet** [comment]
El fin de semana le echo un ojo, pero no tengo mucho tiempo. Habrán cambiado el css de forocoches y habrá que readaptar la regla que buscaba las citas.

**Comment by Saturos1990** [comment]
> El fin de semana le echo un ojo, pero no tengo mucho tiempo. Habrán cambiado el css de forocoches y habrá que readaptar la regla que buscaba las citas.

Ok, muchas gracias!

**Comment by jbonet** [comment]
Arreglado en #11
