### ISSUE TITLE
Borde blanco en instagram embed

### ISSUE THREAD

**Issue by Nisgrak** [pdp-devs/fc-material-design#21]
Tiene como una mota blanca muy molesta. Abro PR jajaja

![image](https://user-images.githubusercontent.com/19597708/79354835-365cb780-7f3d-11ea-8c83-c313ad201719.png)

**Comment by jbonet** [comment]
:qmeparto: pero si no se ve nada!

yo lo uso en modo claro así que no lo había visto

**Comment by Nisgrak** [comment]
Es una tontería pero me molesta mucho, y ahora estoy viendo a ver si puedo hacer que cargue el tema oscuro de twitter si usas el tema oscuro...
