### ISSUE TITLE
Error logo forocoches

### ISSUE THREAD

**Issue by golden900** [pdp-devs/fc-material-design#6]
No aparece el logo de forocoches en el tema, a pesar de estar escrito el base64 en el código. Adjunto captura de cómo sale el logo del foro (el error que indica de imgur) y capturas del código en las que aparecen urls rotas de imgur que tal vez puedan ser el fallo (no obstante, yo sustituí en el código esas imágenes rotas por funcionales en base64 y sigue sin aparecer adecuadamente).
![error1](https://user-images.githubusercontent.com/50753301/60125683-9b67d680-978c-11e9-8bbe-76dee27d2b6c.JPG)
![error2](https://user-images.githubusercontent.com/50753301/60126036-6740e580-978d-11e9-9477-3dfd5c7cd3c0.JPG)
![error3](https://user-images.githubusercontent.com/50753301/60126039-69a33f80-978d-11e9-84d2-e0658f5c7ca7.JPG)

P.S. Soy consciente que uno de los links subidos pertenece a un comentario en el código y no debería afectar a como se ve el tema, no obstante, es lo único que he encontrado. He comprobado que los enlaces correspondientes al logo están adecuadamente puestos en base64, pero aun así sale mal a la hora de navegar por el foro.

**Comment by jbonet** [comment]
Has desinstalado el tema anterior e instalado este desde el UserCSS? 

Has borrado caché?

Por ver qué puede ser ya que no debería referenciar a imgur esa parte del código.

**Comment by golden900** [comment]
Sí, desinstalé el anterior, eliminé Stylish y borré la caché para instalar Stylus y posteriormente usar el usercss del hilo del foro, y aun así sigue saliendo eso. Yo tampoco le veo mucho sentido, ya que he visto que las imágenes que deberían aparecer ahí estan puestas adecuadamente en base64. He revisado muy por encima el código pero como dices, en las partes en las que debe aparecer el logo no hay ningún link de imgur...

**Comment by jbonet** [comment]
Puedes probarlo en otro navegador?

O activando la extensión en modo incógnito? 

Vamos a probar cosas

![image](https://user-images.githubusercontent.com/17141983/60127938-c274d700-9791-11e9-89d4-ea3f41f46bc0.png)

Fíjate que la imagen está en el td que envuelve al img, qué te sale ahí, el link a imgur o el base64?

**Comment by golden900** [comment]
![error](https://user-images.githubusercontent.com/50753301/60128349-b8070d00-9792-11e9-9493-4d1240b0de84.JPG)
Voilá.

He probado modo incognito y otro navegador no basado en Chromium (en firefox) y seguía saliendo igual, no obstante, aquí en Brave, a diferencia de en Firefox al inspeccionar el elemento la parte del código que corresponde a la imagen y su posicion, sale tachada.

**Comment by jbonet** [comment]
Vale ya está solucionado... :qmeparto: 

La imagen en base64 era el error, en la próxima versión se te actualizará, o si reinstalas el tema.

**Comment by golden900** [comment]
Justo la acababa de cambiar en el editor de texto e iba a cargar el tema a Stylus para probar, pero si me confirmas que es eso reinstalo el tema y solucionado. Muchas gracias!!
